#!/usr/bin/env python3

from dgacollection.Cryptolocker import Cryptolocker

import random
import time
import subprocess

# Retrieving domains generated by implementation of
# DGA from https://github.com/pchaigno/dga-collection
domains = (Cryptolocker.domains())
number_domains_generated = (len(Cryptolocker.domains()))

# Limiting sizes for demonstration
# in reality 500-50000 /day (Conficker)
number_domains_poc = 10

# Choose randomly a value
random_value = random.randrange(number_domains_poc)
malicious_server = domains[random_value]
print("The new C2 server is at : " + malicious_server)

subprocess.run(['/update_dns.sh', malicious_server]) 

# Keep the container alive
while True:
    time.sleep(10)