#!/usr/bin/env python3

from dgacollection.Cryptolocker import Cryptolocker

import random
import time

# Retrieving domains generated by implementation of
# DGA from https://github.com/pchaigno/dga-collection
domains = (Cryptolocker.domains())
number_domains_generated = (len(Cryptolocker.domains()))

# Limiting sizes for demonstration
# in reality 500-50000 /day (Conficker)
number_domains_poc = 20

def change_domain(domain):
    """send the new value of the domain for the c2-server to the attacker's DNS

    Args:
        domain (string): domain generated by the DGA and taken randomly using today's seed
    """
    with open("/domain", 'a') as a_writer:
        a_writer.write(domain)

# Choose randomly a value
random_value = random.randrange(number_domains_poc)
malicious_server = domains[random_value]
print("The new C2 server is at : " + malicious_server)
change_domain(malicious_server)

# Keep the container alive
while True:
    time.sleep(10)